# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_delayed_subset <- function(input, subset, row) {
    .Call('_beachmat_apply_delayed_subset', PACKAGE = 'beachmat', input, subset, row)
}

apply_delayed_transpose <- function(input) {
    .Call('_beachmat_apply_delayed_transpose', PACKAGE = 'beachmat', input)
}

apply_delayed_bind <- function(input, row) {
    .Call('_beachmat_apply_delayed_bind', PACKAGE = 'beachmat', input, row)
}

apply_delayed_addition <- function(input, val, row) {
    .Call('_beachmat_apply_delayed_addition', PACKAGE = 'beachmat', input, val, row)
}

apply_delayed_multiplication <- function(input, val, row) {
    .Call('_beachmat_apply_delayed_multiplication', PACKAGE = 'beachmat', input, val, row)
}

apply_delayed_subtraction <- function(input, val, right, row) {
    .Call('_beachmat_apply_delayed_subtraction', PACKAGE = 'beachmat', input, val, right, row)
}

apply_delayed_division <- function(input, val, right, row) {
    .Call('_beachmat_apply_delayed_division', PACKAGE = 'beachmat', input, val, right, row)
}

apply_delayed_log <- function(input, base) {
    .Call('_beachmat_apply_delayed_log', PACKAGE = 'beachmat', input, base)
}

apply_delayed_log1p <- function(input) {
    .Call('_beachmat_apply_delayed_log1p', PACKAGE = 'beachmat', input)
}

apply_delayed_abs <- function(input) {
    .Call('_beachmat_apply_delayed_abs', PACKAGE = 'beachmat', input)
}

apply_delayed_sqrt <- function(input) {
    .Call('_beachmat_apply_delayed_sqrt', PACKAGE = 'beachmat', input)
}

apply_delayed_round <- function(input) {
    .Call('_beachmat_apply_delayed_round', PACKAGE = 'beachmat', input)
}

apply_delayed_exp <- function(input) {
    .Call('_beachmat_apply_delayed_exp', PACKAGE = 'beachmat', input)
}

fragment_sparse_rows <- function(i, p, limits) {
    .Call('_beachmat_fragment_sparse_rows', PACKAGE = 'beachmat', i, p, limits)
}

sparse_subset_index <- function(starts, newp) {
    .Call('_beachmat_sparse_subset_index', PACKAGE = 'beachmat', starts, newp)
}

initialize_sparse_matrix <- function(x, i, p, nrow, ncol, byrow) {
    .Call('_beachmat_initialize_sparse_matrix', PACKAGE = 'beachmat', x, i, p, nrow, ncol, byrow)
}

initialize_unknown_matrix <- function(input) {
    .Call('_beachmat_initialize_unknown_matrix', PACKAGE = 'beachmat', input)
}

