# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apply_delayed_subset <- function(raw_input, subset, row) {
    .Call('_beachmat_apply_delayed_subset', PACKAGE = 'beachmat', raw_input, subset, row)
}

apply_delayed_transpose <- function(raw_input) {
    .Call('_beachmat_apply_delayed_transpose', PACKAGE = 'beachmat', raw_input)
}

apply_delayed_bind <- function(input, row) {
    .Call('_beachmat_apply_delayed_bind', PACKAGE = 'beachmat', input, row)
}

apply_delayed_addition <- function(raw_input, val, row) {
    .Call('_beachmat_apply_delayed_addition', PACKAGE = 'beachmat', raw_input, val, row)
}

apply_delayed_multiplication <- function(raw_input, val, row) {
    .Call('_beachmat_apply_delayed_multiplication', PACKAGE = 'beachmat', raw_input, val, row)
}

apply_delayed_subtraction <- function(raw_input, val, right, row) {
    .Call('_beachmat_apply_delayed_subtraction', PACKAGE = 'beachmat', raw_input, val, right, row)
}

apply_delayed_division <- function(input, val, right, row) {
    .Call('_beachmat_apply_delayed_division', PACKAGE = 'beachmat', input, val, right, row)
}

apply_delayed_log <- function(raw_input, base) {
    .Call('_beachmat_apply_delayed_log', PACKAGE = 'beachmat', raw_input, base)
}

apply_delayed_log1p <- function(raw_input) {
    .Call('_beachmat_apply_delayed_log1p', PACKAGE = 'beachmat', raw_input)
}

apply_delayed_abs <- function(raw_input) {
    .Call('_beachmat_apply_delayed_abs', PACKAGE = 'beachmat', raw_input)
}

apply_delayed_sqrt <- function(raw_input) {
    .Call('_beachmat_apply_delayed_sqrt', PACKAGE = 'beachmat', raw_input)
}

apply_delayed_round <- function(raw_input) {
    .Call('_beachmat_apply_delayed_round', PACKAGE = 'beachmat', raw_input)
}

apply_delayed_exp <- function(raw_input) {
    .Call('_beachmat_apply_delayed_exp', PACKAGE = 'beachmat', raw_input)
}

fragment_sparse_rows <- function(i, p, limits) {
    .Call('_beachmat_fragment_sparse_rows', PACKAGE = 'beachmat', i, p, limits)
}

sparse_subset_index <- function(starts, newp) {
    .Call('_beachmat_sparse_subset_index', PACKAGE = 'beachmat', starts, newp)
}

initialize_sparse_matrix <- function(raw_x, raw_i, raw_p, nrow, ncol, byrow) {
    .Call('_beachmat_initialize_sparse_matrix', PACKAGE = 'beachmat', raw_x, raw_i, raw_p, nrow, ncol, byrow)
}

tatami_dim <- function(input) {
    .Call('_beachmat_tatami_dim', PACKAGE = 'beachmat', input)
}

tatami_column <- function(input, i) {
    .Call('_beachmat_tatami_column', PACKAGE = 'beachmat', input, i)
}

tatami_row <- function(input, i) {
    .Call('_beachmat_tatami_row', PACKAGE = 'beachmat', input, i)
}

initialize_unknown_matrix <- function(input) {
    .Call('_beachmat_initialize_unknown_matrix', PACKAGE = 'beachmat', input)
}

